//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendList
    {
        public int Id { get; set; }
        public string AccountidOne { get; set; }
        public string AccountidTwo { get; set; }
    }
}
